### ISSUE TITLE
Require is not defined

### ISSUE THREAD

**Issue by Eric-Tran** [toddmotto/angular-1-5-components-app#6]
After checking and downloading neccessary dependencies (node, firebase-tools, gulp), npm install, running npm start gives me require is not defined in the browser? I tried this on both the master seed stater and this file same results. 

vendor.js:39766 Uncaught ReferenceError: require is not defined
vendor.js:4640 Uncaught Error: [$injector:modulerr] Failed to instantiate module root due to:
Error: [$injector:modulerr] Failed to instantiate module components due to:
Error: [$injector:modulerr] Failed to instantiate module components.auth due to:
Error: [$injector:modulerr] Failed to instantiate module firebase due to:
Error: [$injector:nomod] Module 'firebase' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.8/$injector/nomod?p0=firebase

**Comment by Eric-Tran** [comment]
Seems like my other projects using babel was interfering. Disabling babel cache or removing the babel.json file in my root system directory solved the problem.

**Comment by Eric-Tran** [comment]
Issue is still there..

**Comment by toddmotto** [comment]
Pushed a fix for this, it was due to `firebase.js` new version which swapped everything out for CommonJS "require" syntax for browser usage which completely broke the bundle as we're not using require in the browser. So I've hard coded the version number here for a temporary fix so I can look into using the CJS format or new distribution format: https://github.com/toddmotto/angular-1-5-components-app/commit/f763457708b906f1488a50073a7b6f02c3c93d9b
